### PR TITLE
Allow usage without global package installation

### LINKED ISSUE #57: Eliminate yeoman installation
The steps can be simplified by not requiring installation of yeoman but instead specify it in npm project creation: 

````shell
npm init yo blockstack
````

Assuming npm >=v6.1.0 which introduced use of a custom package with npm init to scaffold a project.

### PR DESCRIPTION
**Pull request by zone117x**
Resolves https://github.com/blockstack/blockstack-app-generator/issues/57

This installation method also uses `npx` which ensures the latest version of our generator package gets used when the command is ran.

### CODE REVIEW

**Review by moxiegirl — CHANGES_REQUESTED** [review]
@zone117x We should not release this until we have a solution that works in these three environments:

- macOS
- Windows
- Ubuntu Linux

These are three categories of OS most often generating complaints from users about running our tutorials.

**Comment by zone117x** [comment]
Yep that's why it's a draft

**Review by moxiegirl — APPROVED** [review]
I'd remove that **Contributing** heading if it is just hanging there with nothing underneath.  Other than that LGTM

**Comment by zone117x** [comment]
I removed that header and made the testing headers more explicit

**Pull request merged**
