### PR TITLE
yo blockstack:react

### PR DESCRIPTION
**Pull request by estermer**
1. Created a React App For Hello, Blockstack using Webpack

2. Integrated Yeoman for App generation

3. Added tests for Yeoman

4. Edited the README.md to include how to generate the React app using `yo blockstack:react`

I am having some trouble with creating a profile with blockstack because of an error with the current portal, So if someone could look at this and make sure it is in fact logging someone in, I was able to confirm it getting a user to be asked to be authenticated.

Also if anyone has any suggestions on this, it would be greatly appreciated. I tried to make this as similar as the original one done.

### CODE REVIEW

**Comment by larrysalibra** [comment]
Hey @estermer this is really awesome! Sorry to take so long to get back.

It's not working for me because the CORS headers aren't set on the /manifest.json so the Portal is unable to download it for verification:

screen shot 2017-05-09 at 1 15 44 am

This is how @shea256 solved this on his `yo blockstack` generator: https://github.com/blockstack/blockstack-app-generator/blob/master/app/templates/server.js

Think you can do something similar for the reach generator?

Just a heads up, clicking log in doesn't do anything at all in Safari right now because of a bug in `redirectUserToSignIn` in `blockstack.js 0.2.22` - I've opened issue https://github.com/blockstack/blockstack.js/issues/205 about that.

**Comment by estermer** [comment]
I can definitely try and get that fixed. I will do what I can but I don't have an ID to test it with.

**Comment by larrysalibra** [comment]
@estermer Awesome. Thanks! Let me know if you need any help testing!

**Comment by estermer** [comment]
@larrysalibra I am gunna need some help testing. I just need an account which for some reason I cannot get. the portal keeps saying that there was an issue with registering the id. Is there a generic test account I can get into to test the auth?

**Comment by estermer** [comment]
Ok so not sure how but FINALLY I have been able to create a blockstack ID through the browser 🙌  so I believe I can finally test this and work out the kinks. Hopefully we can get this merged in sometime in the next week or 2.

**Comment by larrysalibra** [comment]
That's great to hear! @estermer ! Yes we can definitely merge this in the next couple days if you confirm it works for you

**Comment by dantrevino** [comment]
@estermer can you make this public so that I can try it?  Or is set to be merged soon?  I'd like to play with a react based app.

**Comment by estermer** [comment]
@dantrevino I am currently working out the bug, I hope to have it done within the next week or so.

**Comment by jackzampolin** [comment]
Yes!!! Glad we are updating this!

**Comment by estermer** [comment]
Alright I was able to finally create myself a profile to be able to test a successful login.

Cleared the CORS issue setting the headers in the devServer for webpack.

Also styled it to better match the original.

Quick comments, I noticed in both my generator and the original the user's avatar takes some time to load. Not sure if you guys are working on making those type of calls a little quicker with blockstack.js. It made working with React's event loop a little different then the original app generator example. Other than that I believe this should be good to go now.

Ready for review from @larrysalibra, @shea256, @guylepage3, @pstan26

**Comment by jackzampolin** [comment]
Other than the loadtime issue that @estermer mentioned this looks great. I was able to pull down and run it w/o error. A couple of notes if you are testing from this branch. To setup run the following:

```
$ git checkout -b estermer-react-generator master
$ git pull https://github.com/estermer/blockstack-app-generator.git react-generator
$ npm i && npm link
$ mkdir test && cd test
$ yo blockstack:react
$ npm run start
```
The app should be available at `localhost:8080`

LGTM! 👍

**Comment by larrysalibra** [comment]
Thanks @jackzampolin ! I'll merge this in this afternoon!

**Comment by larrysalibra** [comment]
Thank you so much for this @estermer. Sorry to take so long to get it merged in.

Thanks again @jackzampolin for the testing steps - that saved me from a lot of time of re-remembering how to test yeoman modules locally!

**Comment by estermer** [comment]
AWESOME! thanks @larrysalibra! Yeah I understand it took long because I took forever to get my own end working. But this is great, can't wait to work on more frameworks.

**Pull request merged**
