### PR TITLE
Vue.JS generator

### LINKED ISSUE #12: Create a Vue.JS generator
Another popular framework that is growing and from what I have heard is nicer than React.

It is a light weight, component based, client side framework that would be nice to have a generator for.

### PR DESCRIPTION
**Pull request by estermer**
Closes #12 

I was able to create a hello blockstack generator using Vue.js.

Steps to test:
make sure you have generator-blockstack installed as well as yoeman,
pull down these changes to your local machine,
create a new test folder anywhere and cd into it,
run npm link,
they run yo blockstack:vue

This should locally link the generator to the yeoman command. Once this is merged to master, please make sure it and the react generator are added to the yeoman commands globally since the community has pointed out that the commands are not quite working as shown in the readme.

### CODE REVIEW

**Comment by cryptomental** [comment]
Hi! A small thing...

```
$ yo blockstack:vue

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │      Blockstack app      │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? Are you ready to build a Blockstack app in Vue.JS? Yes
events.js:182
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /sandbox/vue/blockstack-app-generator/vue/templates/src/components/Signin.vue
    at EditionInterface.exports.copy (/sandbox/vue/blockstack-app-generator/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/copy.js:47:3)
```

 this is due to templatePath pointing to Signin.vue, whereas the file is CamelCase 'SignIn.vue':

```
blockstack-app-generator/vue/index.js:        this.templatePath('src/components/Signin.vue'),
```

**Comment by estermer** [comment]
Oh awesome thanks! I didn't catch that when i tested mine but i will get in there and make the quick change!

**Comment by moxiegirl** [comment]
@estermer We have updated our generator CI. If you want to fix the conflicts and resubmit this PR.  Apologies for the long wait.

**Comment by Sahana-Srinivasan** [comment]
Modified the SignIn/Profile components to reflect new version of Blockstack with a slightly different sign-in process. Combined with the repo structure/updated packaging of blockstack-todos to make a "Hello, Blockstack" Vue app geneator in [#54](https://github.com/blockstack/blockstack-app-generator/pull/54).

**Pull request closed without merging**
